---

- shell: /etc/init.d/go-agent status
  register: command_result
  ignore_errors: True

- name: download go agent installation file
  get_url: url=http://download01.thoughtworks.com/go/debian/contrib/go-agent-13.4.1-18342.deb dest=/tmp/go-agent.deb
  when:  "'not found' in command_result.stderr"

- name: install go agent
  command: dpkg -i /tmp/go-agent.deb
  when:  "'not found' in command_result.stderr"

- name: start up go agent
  command: "service go-agent start"
  async: 45
  poll: 10